# -*- coding: utf-8 -*-
"""Exa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cHVGHcJ8lc1R2FKQDmN_F7sVtW2Cc3hx
"""

def numPrimo(n):
  for i in range(2, int(n/2)):
    if(n%i) == 0:
      return False
  return True

def nextPrime(n):
    prime = n + 1
    while True:
        if numPrimo(prime):
            return prime
        prime += 1

def mediana(a,b,c):
    lista = [a,b,c]
    lista.sort()
    return lista[1]

import random
import string

def password():
    longitud = random.randint(7, 10)
    contraseña = ''.join(chr(random.randint(33, 126)) for _ in range(longitud))
    return contraseña

from math import sqrt
import math

def hipotenusa(a,b):
  return (math.sqrt((a**2) + (b**2)))